### ISSUE TITLE
Short neck block error

### ISSUE THREAD

**Issue by benngarnish** [jjburton/cgmTools#117]
` Error: coercing to Unicode: need string or buffer, NoneType found
 Traceback (most recent call last):
   File "C:/Users/BennGarnish/Documents/maya/scripts\cgm\core\cgm_General.py", line 993, in __call__
     cgmException(Exception,err)
   File "C:/Users/BennGarnish/Documents/maya/scripts\cgm\core\cgm_General.py", line 982, in __call__
     try:return self._func( *self._args, **self._kwargs )
   File "C:/Users/BennGarnish/Documents/maya/scripts\cgm\core\mrs\Builder.py", line 3161, in uiFunc_block_create
     blockProfile = blockProfile)
   File "C:/Users/BennGarnish/Documents/maya/scripts\cgm\core\cgm_Meta.py", line 6929, in createMetaNode
     cgmGEN.cgmExceptCB(Exception,err)
   File "C:/Users/BennGarnish/Documents/maya/scripts\cgm\core\cgm_Meta.py", line 6915, in createMetaNode
     return _call(*args,**kws)
   File "C:/Users/BennGarnish/Documents/maya/scripts\cgm\core\mrs\RigBlocks.py", line 288, in __init__
     elif not self.verify(blockType,side= _side):
   File "C:/Users/BennGarnish/Documents/maya/scripts\cgm\core\mrs\RigBlocks.py", line 387, in verify
     return self.UTILS.verify(self,blockType,size,side,forceReset)
   File "C:/Users/BennGarnish/Documents/maya/scripts\cgm\core\mrs\lib\block_utils.py", line 437, in verify
     except Exception,err:cgmGEN.cgmExceptCB(Exception,err)
   File "C:/Users/BennGarnish/Documents/maya/scripts\cgm\core\mrs\lib\block_utils.py", line 431, in verify
     self.doName()
   File "C:/Users/BennGarnish/Documents/maya/scripts\cgm\core\mrs\RigBlocks.py", line 390, in doName
     return self.atUtils('doName')
   File "C:/Users/BennGarnish/Documents/maya/scripts\cgm\core\mrs\RigBlocks.py", line 1152, in atBlockUtils
     return getattr(BLOCKUTILS,func)(self,*args,**kws)
   File "C:/Users/BennGarnish/Documents/maya/scripts\cgm\core\mrs\lib\block_utils.py", line 585, in doName
     if _d['cgmName'] in _blockProfile:
 TypeError: coercing to Unicode: need string or buffer, NoneType found  `

Currently in MRSDEV branch running 2020.3.1.1

**Comment by jjburton** [comment]
@benngarnish | I can't replicate. Just built a default short neck head fine. That error dump is a weird one, not sure why anything off would be there.

- Did you do change any settings on the base settings?
- Throw your template up on the MRS Makers Open and I'll take a look.

**Comment by benngarnish** [comment]
Thanks Josh:
Template file: https://www.dropbox.com/s/0sut7rru4jxcl74/Ch_M_Adult_Coughing_01.ma?dl=0

**Comment by benngarnish** [comment]
I too in a new fresh scene was bale to build the spine and head blocks.
Not sure what is up in the template file ☝️

**Comment by jjburton** [comment]
@benngarnish  | Is it an old template? Will look in a few.

**Comment by jjburton** [comment]
@benngarnish |

1. There's no head in the file. 
2. The other blocks are over a year old, things have changed a bit :)

You need to to update or rebuild your blocks and I think you'll be okay. You could try just reverifying them and see if they build but that's pretty old and I think some wiring has changed since then.

**Comment by benngarnish** [comment]
That’s super weird as I built this template from scratch this afternoon.

**Comment by jjburton** [comment]
@benngarnish | see if you can replicate the bug. Tried a bit more and can't on my end.
