### ISSUE TITLE
Importing a block and trying to mirror issue

### ISSUE THREAD

**Issue by benngarnish** [jjburton/cgmTools#125]
`Error: More than one object matches name: seg_index_lever_blockHandle_1_clusterHandle
Traceback (most recent call last):
  File "D:\Git\cgmtools\mayaTools\cgm\core\cgm_General.py", line 993, in __call__
    cgmException(Exception,err)
  File "D:\Git\cgmtools\mayaTools\cgm\core\cgm_General.py", line 982, in __call__
    try:return self._func( *self._args, **self._kwargs )
  File "D:\Git\cgmtools\mayaTools\cgm\core\mrs\Builder.py", line 3442, in uiFunc_contextBlockCall
    res = getattr(mBlock,args[0])(*args[1:],**kws) or None
  File "D:\Git\cgmtools\mayaTools\cgm\core\mrs\RigBlocks.py", line 1152, in atBlockUtils
    return getattr(BLOCKUTILS,func)(self,*args,**kws)
  File "D:\Git\cgmtools\mayaTools\cgm\core\mrs\lib\block_utils.py", line 3915, in blockMirror_create
    except Exception,err:cgmGEN.cgmException(Exception,err)
  File "D:\Git\cgmtools\mayaTools\cgm\core\mrs\lib\block_utils.py", line 3912, in blockMirror_create
    blockDat_load(mMirror,useMirror=True,redefine=True)
  File "D:\Git\cgmtools\mayaTools\cgm\core\mrs\lib\block_utils.py", line 4907, in blockDat_load
    except Exception,err:cgmGEN.cgmException(Exception,err)
  File "D:\Git\cgmtools\mayaTools\cgm\core\mrs\lib\block_utils.py", line 4856, in blockDat_load
    self.p_blockState = 1
  File "D:\Git\cgmtools\mayaTools\Red9\core\Red9_Meta.py", line 616, in wrapper
    raise StandardError(StandardError(err), traceback)
StandardError: (StandardError(ValueError(u'More than one object matches name: seg_index_lever_blockHandle_1_clusterHandle',),), <traceback object at 0x000001A32FBE0488>)`

**Comment by jjburton** [comment]
@benngarnish  | 
Post your file somewhere I can see it. Thanks mate.

**Comment by benngarnish** [comment]
https://www.dropbox.com/s/81qi2chsochcte4/TvHead_Test_template_03.mb?dl=0

**Comment by jjburton** [comment]
3.3.2.20 patch up
