### ISSUE TITLE
Spline Block push to preRig state error

### ISSUE THREAD

**Issue by benngarnish** [jjburton/cgmTools#216]
` cgm.core.mrs.Builder : ===========================================================================  
 Error: cgm.core.lib.curve_Utils : STOP USING THIS CALL: returnSplitCurveList  
 Warning: Object, 'pelvis_preHandle_master_grp5|pelvis_preHandle|pelvis_preHandle_zeroGroup', skipped. It is already a child of the parent, 'pelvis_preHandle'.  
/// prerig_handlesLayout   ///---------------------------------------------------------------------------
 file: D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\lib\block_utils.py
  Local dat...
{'_str_func': 'prerig_handlesLayout',
 'curve': 'cubic',
 'err': ValueError('|alongLine| >> Need at least 3 objects',),
 'idx_end': 1,
 'idx_endNew': 1,
 'idx_start': 0,
 'idx_startNew': 0,
 'mEnd': (node: 'chest_preHandle' | mClass: cgmObject | class: <class 'cgm.core.cgm_Meta.cgmObject'>),
 'mObj': (node: 'chest_preHandle' | mClass: cgmObject | class: <class 'cgm.core.cgm_Meta.cgmObject'>),
 'mStart': (node: 'pelvis_preHandle' | mClass: cgmObject | class: <class 'cgm.core.cgm_Meta.cgmObject'>),
 'ml_preUse': [(node: 'pelvis_preHandle' | mClass: cgmObject | class: <class 'cgm.core.cgm_Meta.cgmObject'>),
               (node: 'chest_preHandle' | mClass: cgmObject | class: <class 'cgm.core.cgm_Meta.cgmObject'>)],
 'ml_prerig': [(node: 'pelvis_preHandle' | mClass: cgmObject | class: <class 'cgm.core.cgm_Meta.cgmObject'>),
               (node: 'chest_preHandle' | mClass: cgmObject | class: <class 'cgm.core.cgm_Meta.cgmObject'>)],
 'ml_toSnap': [(node: 'pelvis_preHandle' | mClass: cgmObject | class: <class 'cgm.core.cgm_Meta.cgmObject'>),
               (node: 'chest_preHandle' | mClass: cgmObject | class: <class 'cgm.core.cgm_Meta.cgmObject'>)],
 'mode': 'even',
 'self': (node: 'spine_up_segmentBlock' | mClass: cgmRigBlock | class: <class 'cgm.core.mrs.RigBlocks.cgmRigBlock'>),
 'spans': 2}
...///
 cgm.core.cgm_General : Func: uiFunc_contextBlockCall  
 cgm.core.cgm_General : args: ('changeState', 'prerig')  
 cgm.core.cgm_General : kws: {'forceNew': True}  
 cgm.core.cgm_General : |alongLine| >> Need at least 3 objects  
/// __call__   ///---------------------------------------------------------------------------
 file: D:\Git\cgmToolsForked\mayaTools\cgm\core\cgm_General.py
  Args...
      False
  Local dat...
{'a': '|alongLine| >> Need at least 3 objects',
 'err': ValueError('|alongLine| >> Need at least 3 objects',),
 'self': <cgm.core.cgm_General.Callback object at 0x0000026D117321D0>}
...///
 Error: |alongLine| >> Need at least 3 objects
 Traceback (most recent call last):
   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\cgm_General.py", line 1008, in __call__
     cgmException(Exception,err)
   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\cgm_General.py", line 997, in __call__
     try:return self._func( *self._args, **self._kwargs )
   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\Builder.py", line 6070, in uiFunc_contextBlockCall
     res = getattr(mBlock,args[0])(*args[1:],**kws) or None
   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\RigBlocks.py", line 895, in changeState
     _res = self.atUtils('changeState',*args,**kws)
   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\RigBlocks.py", line 1157, in atBlockUtils
     return getattr(BLOCKUTILS,func)(self,*args,**kws)
   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\lib\block_utils.py", line 7999, in changeState
     if not d_upStateFunctions[doState](self,**kws):
   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\lib\block_utils.py", line 7555, in prerig
     mBlockModule.prerig(self)
   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\blocks\organic\segment.py", line 1039, in prerig
     self.atUtils('prerig_handlesLayout','even','cubic',2)
   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\RigBlocks.py", line 1157, in atBlockUtils
     return getattr(BLOCKUTILS,func)(self,*args,**kws)
   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\lib\block_utils.py", line 10463, in prerig_handlesLayout
     cgmGEN.cgmException(Exception,err)
   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\lib\block_utils.py", line 10461, in prerig_handlesLayout
     return ARRANGE.alongLine([mObj.mNode for mObj in ml_toSnap],mode,curve,spans)
   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\lib\arrange_utils.py", line 120, in alongLine
     raise ValueError,"|{0}| >> Need at least 3 objects".format(_str_func)
 ValueError: |alongLine| >> Need at least 3 objects  
select -cl  ;`

**Comment by jjburton** [comment]
Need at least 3 controls/joints
