### ISSUE TITLE
Visualise rig shapes error

### ISSUE THREAD

**Issue by benngarnish** [jjburton/cgmTools#231]
```# Error: FAIL || [ R_arm__limbBlock1 ] >> --------------------------------------------------------------------------------
# Traceback (most recent call last):
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\cgm_General.py", line 1008, in __call__
#     cgmException(Exception,err)
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\cgm_General.py", line 997, in __call__
#     try:return self._func( *self._args, **self._kwargs )
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\Builder.py", line 6075, in uiFunc_contextBlockCall
#     res = getattr(mBlock,args[0])(*args[1:],**kws) or None
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\RigBlocks.py", line 1157, in atBlockUtils
#     return getattr(BLOCKUTILS,func)(self,*args,**kws)
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\lib\block_utils.py", line 11509, in shapes_castTest
#     mFac = self.asRigFactory()
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\RigBlocks.py", line 1098, in asRigFactory
#     return rigFactory(self,*a,**kws)
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\RigBlocks.py", line 3064, in __init__
#     raise ValueError,cgmGEN.logString_start("FAIL || [ {0} ]".format(self.mBlock.p_nameShort))
# ValueError: FAIL || [ R_arm__limbBlock1 ] >> -------------------------------------------------------------------------------- # ```

**Comment by jjburton** [comment]
What's the block state?

**Comment by benngarnish** [comment]
PreRig

**Comment by jjburton** [comment]
you need to be in skeleton state

**Comment by jjburton** [comment]
I'll add a catch for that.

**Comment by benngarnish** [comment]
At Skeleton state:

```# Error: 'list' object has no attribute 'mNode'
# Traceback (most recent call last):
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\cgm_General.py", line 1008, in __call__
#     cgmException(Exception,err)
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\cgm_General.py", line 997, in __call__
#     try:return self._func( *self._args, **self._kwargs )
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\Builder.py", line 6075, in uiFunc_contextBlockCall
#     res = getattr(mBlock,args[0])(*args[1:],**kws) or None
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\RigBlocks.py", line 1157, in atBlockUtils
#     return getattr(BLOCKUTILS,func)(self,*args,**kws)
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\lib\block_utils.py", line 11509, in shapes_castTest
#     mFac = self.asRigFactory()
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\RigBlocks.py", line 1098, in asRigFactory
#     return rigFactory(self,*a,**kws)
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\RigBlocks.py", line 3081, in __init__
#     self.fnc_check_module()
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\RigBlocks.py", line 3292, in fnc_check_module
#     mc.editDisplayLayerMembers(_mPuppet.controlLayer.mNode, _mModule.mNode,noRecurse=True)
# AttributeError: 'list' object has no attribute 'mNode' # ```

**Comment by jjburton** [comment]
That looks like the control layer hasn't been built yet or the rig module hasn't built. Looks like control layer issue. What state is your master at?

**Comment by benngarnish** [comment]
Is there an option to create the control layer?

**Comment by benngarnish** [comment]
Actually I got it by pushing Master back to form then back to PreRig.

Maybe a call in the menu to re-create this?

**Comment by jjburton** [comment]
master is the holder for that. We can always add more buttons but it does get daunting. Just make sure your master is a pre or above. It should be at skeleton anyway if you need a sub module at it :)

**Comment by benngarnish** [comment]
I just found that sometimes I loose the control layer.
Didn't realise that Master held that info and by pushing back to form and then to preRig again brings it back 👍

**Comment by jjburton** [comment]
I've not really run into that. I'm wondering what workflow is hitting that. Maybe you can walk me through your workflow sometime.

**Comment by benngarnish** [comment]
@jjburton With the casting...
Is there a way to have a variation in casting?
Example would be a spine:
The chest has a larger control shape due to the way I move the chest preRig handle
However, the pelvis is quite tight and would like it to cast in the opposite direction than the chest to get a larger control shape

This possible?

**Comment by jjburton** [comment]
Anything is possible :) I'd like to let this new tech simmer a bit before adding too much. For a case like that I'd probably just fix it post build and or replace the shape after build. I do that sometimes. I'm currently using simple segments for toon heads and I use the root for the 'head look'. I swap the shape after build for an arrow on those assets. It takes like 10 seconds.
