### ISSUE TITLE
Handle block not able to build proxyMesh

### ISSUE THREAD

**Issue by benngarnish** [jjburton/cgmTools#232]
```# Error: object of type 'bool' has no len()
# Traceback (most recent call last):
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\cgm_General.py", line 1008, in __call__
#     cgmException(Exception,err)
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\cgm_General.py", line 997, in __call__
#     try:return self._func( *self._args, **self._kwargs )
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\cgm_General.py", line 1501, in wrapper
#     cgmException(Exception,err,traceback)
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\cgm_General.py", line 1480, in wrapper
#     res=func(*args,**kws)
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\Builder.py", line 3790, in uiFunc_process
#     self.mPuppet.atUtils('rigNodes_setAttr','ihi',0,self.uiPB_test)
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\RigBlocks.py", line 3964, in atUtils
#     return getattr(PUPPETUTILS,func)(self,*args,**kws)
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\cgm_General.py", line 1501, in wrapper
#     cgmException(Exception,err,traceback)
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\cgm_General.py", line 1480, in wrapper
#     res=func(*args,**kws)
#   File "D:\Git\cgmToolsForked\mayaTools\cgm\core\mrs\lib\puppet_utils.py", line 1194, in rigNodes_setAttr
#     int_lenNodes = len(l_dat)
# TypeError: object of type 'bool' has no len() # ```

**Comment by benngarnish** [comment]
From batch:
`cgm.core.mrs.lib.batch_utils : ERROR : local variable 'ml_proxy' referenced before assignment`
