### ISSUE TITLE
Block picker not loading

### ISSUE THREAD

**Issue by benngarnish** [jjburton/cgmTools#349]
This is happening when I have other CGM UI's open.

I have to lose all UI's and then the block picker UI loads fine.

**Stack trace:**

```py
# cgm.core.cgm_General : Release: MRSDAILY | 22.11.21.1
# Error: Object 'MelButton365__' not found.
# Traceback (most recent call last):
#   File "D:\1 Projects\dev\maya\cgmTools\mayaTools\cgm\core\cgm_General.py", line 1014, in __call__
#     cgmException(Exception,err)
#   File "D:\1 Projects\dev\maya\cgmTools\mayaTools\cgm\core\cgm_General.py", line 1003, in __call__
#     try:return self._func( *self._args, **self._kwargs )
#   File "D:\1 Projects\dev\maya\cgmTools\mayaTools\cgm\core\mrs\Builder.py", line 6210, in uiFunc_contextBlockCall
#     return blockPicker_get(ml_blocks[0])
#   File "D:\1 Projects\dev\maya\cgmTools\mayaTools\cgm\core\mrs\Builder.py", line 211, in blockPicker_get
#     BLOCKPICKER.uiFunc_loadBlock(mBlock)
#   File "D:\1 Projects\dev\maya\cgmTools\mayaTools\cgm\core\mrs\Builder.py", line 1778, in uiFunc_loadBlock
#     self.uiStr_header(edit=1, label = 'Syncing')
#   File "D:\1 Projects\dev\maya\cgmTools\mayaTools\cgm\core\lib\zoo\baseMelUI.py", line 165, in __call__
#     return self.WIDGET_CMD( unicode( self ), *a, **kw )
# RuntimeError: Object 'MelButton365__' not found. # 
# cgm.core.mrs.Builder : cached...
# Error: window: Object 'mrsBlockPicker' not found.
# Traceback (most recent call last):
#   File "D:\1 Projects\dev\maya\cgmTools\mayaTools\cgm\core\tools\lib\tool_chunks.py", line 853, in <lambda>
#     c=lambda *a:TOOLCALLS.mrsBlockPicker())
#   File "D:\1 Projects\dev\maya\cgmTools\mayaTools\cgm\core\tools\lib\tool_calls.py", line 51, in mrsBlockPicker
#     MRSBUILDER.blockPicker_get()
#   File "D:\1 Projects\dev\maya\cgmTools\mayaTools\cgm\core\mrs\Builder.py", line 213, in blockPicker_get
#     if not BLOCKPICKER(q=1, visible=True):
#   File "D:\1 Projects\dev\maya\cgmTools\mayaTools\cgm\core\lib\zoo\baseMelUI.py", line 2530, in __call__
#     return cmd.window( self, *a, **kw )
# RuntimeError: window: Object 'mrsBlockPicker' not found. #

**Comment by jjburton** [comment]
Maya version? Can't replicate offhand. Can you please post replicate case? What's open, what do you do?

**Comment by benngarnish** [comment]
Hey mate. 

Maya version 2022

**Comment by jjburton** [comment]
Is this still a bug?
